version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /mnt/d/data:/var/lib/mysql